defaults:
  - user: default
  - machine: local
  - callback: base 
  - data: bop
  - model: ISM_sam
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
   dir: .

save_dir: ./log/${name_exp}
name_exp: sam
dataset_name: